### ISSUE TITLE
SNV : Scroll blocked on edit mode + on AS

### ISSUE THREAD

**Issue by Jihed525** [Meeds-io/notes#917]
Scenario
Add an SNV on spaceX activity stream or global stream 
Add an image and text in the full page editor. The content should be enough long to need to scroll.
Save it
on space x stream, Edit SNV in the simple editor 
Try to scroll down
Actual:
Scroll is blocked
Expected behavior
scrolling on current page up/down should be possible.

https://community.exoplatform.com/portal/dw/tasks/taskDetail/68519
https://community.exoplatform.com/portal/dw/tasks/taskDetail/68518

**Comment by boubaker** [comment]
To move to https://github.com/Meeds-io/meeds
